

name: R

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
    
    
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.HEAAN_SDK_JKIM }}'
        mkdir -p ~/.ssh
        ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
      #- name: Checkout code
        #uses: actions/checkout@v2
        #with:
          #repository: git@github.com:CryptoLabInc/packages.git
          #ref: main
      - name: Set up SSH key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.songhpark1 }}'
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts

        
      - name: check file
        run: ls -al
     
