# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv .venv
          source /home/runner/work/test.ci.R/test.ci.R/.venv/bin/activate
          cd /home/runner/work/test.ci.R/test.ci.R/.venv/lib/python3.8/site-packages
          curl -LJO -u SongHyeopPark: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 https://github.com/CryptoLabInc/packages/tree/main/sdk/heaan_sdk-0.0.2-cp38-cp38-linux_x86_64.whl
          curl -LJO -u SongHyeopPark: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 https://github.com/CryptoLabInc/packages/tree/main/heaan/heaan.cpython-38d-x86_64-linux-gnu.so
          curl -LJO -u SongHyeopPark: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 https://github.com/CryptoLabInc/packages/tree/main/heaan/piheaan.cpython-38d-x86_64-linux-gnu.so

          #pip install heaan_sdk-0.0.2-cp38-cp38-linux_x86_64.whl
