name: Install Wheel

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: check path
      run: ls -al
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install wheel


    - name: Install Wheel
      run: |
        pip install heaan_sdk-0.0.2-cp38-cp38-linux_x86_64.whl
